### ISSUE TITLE
Providing CORS support at https://w3id.org/ore/context

### ISSUE THREAD

**Issue by ocorcho** [stain/ore#11]
This URI currently redirects to http://stain.github.io/ore/context.json, which contains the JSON-LD context to be used. While this is perfectly ok in general, when using services like the JSON-LD playground (http://json-ld.org/playground/), which is very useful to test the generated JSON-LD, the context cannot be dereferenced correctly.

It may be that CORS is not supported, although there may be another reason as well for this misbehaviour.

**Comment by stain** [comment]
It now redirects to http://www.openarchives.org/ore/0.9/context.json
